networks:
  host:

services:
  redis:
    container_name: ${CONTAINER_NAME}
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - host
    ports:
      - ${HOST_IP}:${APP_PORT}:80
    volumes:
      - /opt/kkdash/www:/usr/share/nginx/html:ro
